//! Finite quotient algebras of Gröbner bases.

mod linear;
mod spectra;
mod staircase;

pub use linear::MultiplicationMatrix;
pub use spectra::UnivariatePolynomial;

use linear::QuotientBudget;

use std::fmt;
use std::mem::size_of;

use crate::arithmetic::ArithmeticError;
use crate::compute::{Budget, ComputeError, ComputeLimits, RunError, TICK};
use crate::ideal::GroebnerBasis;
use crate::normal_form::{self, DivisionStop};
use crate::poly::{Monomial, Polynomial, Term, heap_exps_bytes};
use crate::ring::{Domain, DomainOps};

type CoordinateVector<D> = Vec<Option<<D as Domain>::Coeff>>;
type MatrixColumns<D> = Vec<CoordinateVector<D>>;
type MatrixColumn<D> = (CoordinateVector<D>, usize);

/// Why a finite quotient operation stopped.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum QuotientError {
    /// The leading monomial ideal is not zero-dimensional.
    NotFinite,
    /// An operand belongs to a different polynomial ring.
    RingMismatch,
    /// A required exponent is above the width supported by the ring.
    ExponentLimit {
        /// The largest value one exponent can hold.
        limit: u32,
    },
    /// The deadline passed.
    Timeout,
    /// The tracked live data passed the memory limit.
    MemoryLimitExceeded,
}

impl fmt::Display for QuotientError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            QuotientError::NotFinite => {
                f.write_str("the leading monomial ideal is not zero-dimensional")
            }
            QuotientError::RingMismatch => f.write_str("a polynomial belongs to a different ring"),
            QuotientError::ExponentLimit { limit } => write!(
                f,
                "the quotient computation reached an exponent above {limit}, which is the largest one exponent holds"
            ),
            QuotientError::Timeout => f.write_str("the quotient computation passed its deadline"),
            QuotientError::MemoryLimitExceeded => {
                f.write_str("the quotient computation passed its memory limit")
            }
        }
    }
}

impl std::error::Error for QuotientError {}

impl From<DivisionStop> for QuotientError {
    fn from(stop: DivisionStop) -> Self {
        match stop {
            DivisionStop::ExponentLimit => QuotientError::ExponentLimit {
                limit: u16::MAX as u32,
            },
            DivisionStop::Run(error) => quotient_run_error(error),
        }
    }
}

fn quotient_compute_error(error: ComputeError) -> QuotientError {
    match error {
        ComputeError::MemoryLimitExceeded => QuotientError::MemoryLimitExceeded,
        ComputeError::Timeout => QuotientError::Timeout,
        ComputeError::ExponentLimit { limit } => QuotientError::ExponentLimit { limit },
        ComputeError::DegreeLimit { .. }
        | ComputeError::TableFull
        | ComputeError::PrimesExhausted => {
            unreachable!("quotient budget operations do not report this stop")
        }
    }
}

fn quotient_run_error(error: RunError) -> QuotientError {
    match error {
        RunError::Compute(error) => quotient_compute_error(error),
        RunError::Cancelled => QuotientError::Timeout,
    }
}

fn quotient_arithmetic_error(error: ArithmeticError) -> QuotientError {
    match error {
        ArithmeticError::RingMismatch => QuotientError::RingMismatch,
        ArithmeticError::ExponentLimit { limit } => QuotientError::ExponentLimit { limit },
        ArithmeticError::Timeout => QuotientError::Timeout,
        ArithmeticError::MemoryLimitExceeded => QuotientError::MemoryLimitExceeded,
        ArithmeticError::CoefficientConversion(_) => {
            unreachable!("quotient arithmetic does not convert coefficients")
        }
    }
}

/// A finite-dimensional polynomial quotient in the fixed grevlex basis.
///
/// The value retains a clone of the source basis, including rational lift
/// metadata. Its standard monomial list uses exponent vectors in ascending
/// grevlex order. Derived values are computed from the retained basis. Over
/// `Q`, they describe only the ideal generated by that basis. Its [`lift`]
/// record says whether the run establishes containment of the input ideal;
/// `Unchanged` establishes nothing.
///
/// [`lift`]: GroebnerBasis::lift
#[derive(Clone, Debug)]
pub struct FiniteQuotient<D: Domain = crate::ring::PrimeField> {
    source_basis: GroebnerBasis<D>,
    staircase: staircase::Staircase,
}

impl<D: Domain> FiniteQuotient<D> {
    /// The ring of the quotient.
    pub fn ring(&self) -> &crate::ring::PolynomialRing<D> {
        self.source_basis.ring()
    }

    /// The Gröbner basis that defines this quotient.
    ///
    /// The returned basis is a clone retained at construction, so rational
    /// lift metadata remains available through `GroebnerBasis::lift`.
    pub fn source_basis(&self) -> &GroebnerBasis<D> {
        &self.source_basis
    }

    /// The standard monomials as exponent vectors in ascending grevlex order.
    ///
    /// Each vector has one exponent per ring variable. The empty vector is
    /// the basis of a zero-variable constant quotient.
    pub fn standard_monomials(&self) -> &[Vec<u16>] {
        &self.staircase.basis
    }

    /// The vector-space dimension of the quotient over its coefficient domain.
    pub fn vector_space_dimension(&self) -> usize {
        self.staircase.basis.len()
    }

    /// Reduce `polynomial` to its normal-form residue.
    ///
    /// The budget covers the retained source basis, the division, and the
    /// returned remainder. The result is a polynomial in the same ring.
    pub fn reduce(
        &self,
        polynomial: &Polynomial<D>,
        budget: Budget,
    ) -> Result<Polynomial<D>, QuotientError> {
        self.check_ring(polynomial)?;
        let limits = ComputeLimits::of_budget(&budget);
        self.reduce_with_limits(polynomial, &limits)
    }

    /// Return coordinates of a polynomial residue in the standard basis.
    ///
    /// The vector follows [`FiniteQuotient::standard_monomials`]. `None` represents a zero
    /// coordinate. The polynomial is reduced before its coordinates are read.
    pub fn coordinates(
        &self,
        polynomial: &Polynomial<D>,
        budget: Budget,
    ) -> Result<Vec<Option<D::Coeff>>, QuotientError> {
        self.check_ring(polynomial)?;
        let limits = ComputeLimits::of_budget(&budget);
        self.coordinates_with_limits(polynomial, &limits)
    }

    /// Add two polynomial residues and reduce the result.
    pub fn add(
        &self,
        left: &Polynomial<D>,
        right: &Polynomial<D>,
        budget: Budget,
    ) -> Result<Polynomial<D>, QuotientError> {
        self.check_ring(left)?;
        self.check_ring(right)?;
        let limits = ComputeLimits::of_budget(&budget);
        self.add_with_limits(left, right, &limits)
    }

    /// Multiply two polynomial residues and reduce the result.
    pub fn multiply(
        &self,
        left: &Polynomial<D>,
        right: &Polynomial<D>,
        budget: Budget,
    ) -> Result<Polynomial<D>, QuotientError> {
        self.check_ring(left)?;
        self.check_ring(right)?;
        let limits = ComputeLimits::of_budget(&budget);
        self.multiply_with_limits(left, right, &limits)
    }

    /// Raise a polynomial residue to a nonnegative integer power.
    pub fn pow(
        &self,
        polynomial: &Polynomial<D>,
        exponent: usize,
        budget: Budget,
    ) -> Result<Polynomial<D>, QuotientError> {
        self.check_ring(polynomial)?;
        let limits = ComputeLimits::of_budget(&budget);
        let mut result = self.ring().one();
        result = self.reduce_with_limits(&result, &limits)?;
        let mut base = self.reduce_with_limits(polynomial, &limits)?;
        let mut power = exponent;
        while power != 0 {
            self.check_limits(
                &limits,
                self.retained_bytes()
                    .saturating_add(result.retained_bytes()),
            )?;
            if power & 1 == 1 {
                result = self.multiply_with_limits(&result, &base, &limits)?;
            }
            power >>= 1;
            if power != 0 {
                base = self.multiply_with_limits(&base, &base, &limits)?;
            }
        }
        Ok(result)
    }

    /// Build the matrix of multiplication by a residue class.
    ///
    /// Columns follow [`FiniteQuotient::standard_monomials`]. Column `j` contains the
    /// coordinates of `polynomial` times basis monomial `j`. The matrix is
    /// built on demand, and the budget covers every column and all `D²`
    /// returned entries.
    pub fn multiplication_matrix(
        &self,
        polynomial: &Polynomial<D>,
        budget: Budget,
    ) -> Result<MultiplicationMatrix<D>, QuotientError> {
        self.check_ring(polynomial)?;
        let limits = ComputeLimits::of_budget(&budget);
        self.multiplication_matrix_with_limits(polynomial, &limits)
    }

    fn multiplication_matrix_with_limits(
        &self,
        polynomial: &Polynomial<D>,
        limits: &ComputeLimits,
    ) -> Result<MultiplicationMatrix<D>, QuotientError> {
        let held = self
            .retained_bytes()
            .saturating_add(polynomial.retained_bytes());
        let mut meter = QuotientBudget::new(limits, held).map_err(quotient_compute_error)?;
        let dimension = self.vector_space_dimension();
        let outer_bytes = dimension.saturating_mul(size_of::<Vec<Option<D::Coeff>>>());
        meter.reserve(outer_bytes).map_err(quotient_compute_error)?;
        let (columns, column_bytes) =
            self.matrix_columns(polynomial, limits, dimension, &mut meter)?;

        let matrix = MultiplicationMatrix::from_columns(self.ring().clone(), columns, &mut meter)
            .map_err(quotient_compute_error);
        meter.release(column_bytes);
        meter.release(outer_bytes);
        matrix
    }

    fn matrix_columns(
        &self,
        polynomial: &Polynomial<D>,
        limits: &ComputeLimits,
        dimension: usize,
        meter: &mut QuotientBudget<'_>,
    ) -> Result<(MatrixColumns<D>, usize), QuotientError> {
        let mut columns = Vec::with_capacity(dimension);
        let mut column_bytes = 0usize;
        for monomial in self.standard_monomials_internal() {
            let (coordinates, bytes) =
                self.matrix_column(polynomial, monomial, limits, dimension, meter)?;
            column_bytes = column_bytes.saturating_add(bytes);
            columns.push(coordinates);
        }
        Ok((columns, column_bytes))
    }

    fn matrix_column(
        &self,
        polynomial: &Polynomial<D>,
        monomial: &Monomial,
        limits: &ComputeLimits,
        dimension: usize,
        meter: &mut QuotientBudget<'_>,
    ) -> Result<MatrixColumn<D>, QuotientError> {
        meter.check().map_err(quotient_compute_error)?;
        let basis_polynomial = self.monomial_polynomial(monomial);
        let basis_bytes =
            size_of::<Polynomial<D>>().saturating_add(basis_polynomial.retained_bytes());
        meter.reserve(basis_bytes).map_err(quotient_compute_error)?;
        let product_bytes = multiply_estimate_bytes(polynomial, &basis_polynomial);
        meter
            .reserve(product_bytes)
            .map_err(quotient_compute_error)?;
        let residue = self.multiply_with_limits(polynomial, &basis_polynomial, limits);
        meter.release(product_bytes);
        meter.release(basis_bytes);
        let residue = residue?;

        let residue_bytes = size_of::<Polynomial<D>>().saturating_add(residue.retained_bytes());
        meter
            .reserve(residue_bytes)
            .map_err(quotient_compute_error)?;
        let coordinates_bytes = dimension
            .saturating_mul(size_of::<Option<D::Coeff>>())
            .saturating_add(residue.coefficient_bytes());
        if let Err(error) = meter.reserve(coordinates_bytes) {
            meter.release(residue_bytes);
            return Err(quotient_compute_error(error));
        }
        let coordinates =
            self.coordinates_of_reduced(&residue, limits, polynomial.retained_bytes());
        meter.release(residue_bytes);
        if coordinates.is_err() {
            meter.release(coordinates_bytes);
        }
        Ok((coordinates?, coordinates_bytes))
    }

    /// Compute the characteristic polynomial of multiplication by a residue.
    pub fn characteristic_polynomial(
        &self,
        polynomial: &Polynomial<D>,
        budget: Budget,
    ) -> Result<UnivariatePolynomial<D>, QuotientError> {
        self.check_ring(polynomial)?;
        let limits = ComputeLimits::of_budget(&budget);
        let matrix = self.multiplication_matrix_with_limits(polynomial, &limits)?;
        let held = self
            .retained_bytes()
            .saturating_add(polynomial.retained_bytes())
            .saturating_add(matrix.heap_bytes());
        let mut meter = QuotientBudget::new(&limits, held).map_err(quotient_compute_error)?;
        spectra::characteristic_polynomial(&matrix, &mut meter).map_err(quotient_compute_error)
    }

    /// Compute the minimal polynomial of multiplication by a residue.
    pub fn minimal_polynomial(
        &self,
        polynomial: &Polynomial<D>,
        budget: Budget,
    ) -> Result<UnivariatePolynomial<D>, QuotientError> {
        self.check_ring(polynomial)?;
        let limits = ComputeLimits::of_budget(&budget);
        let matrix = self.multiplication_matrix_with_limits(polynomial, &limits)?;
        let held = self
            .retained_bytes()
            .saturating_add(polynomial.retained_bytes())
            .saturating_add(matrix.heap_bytes());
        let mut meter = QuotientBudget::new(&limits, held).map_err(quotient_compute_error)?;
        spectra::minimal_polynomial(&matrix, &mut meter).map_err(quotient_compute_error)
    }

    /// Estimate bytes retained by the quotient and its source basis.
    ///
    /// The estimate includes owned vector capacities and coefficient payloads.
    /// Ring storage is shared by the source and its polynomials. Allocator
    /// metadata is outside the estimate.
    pub(crate) fn retained_bytes(&self) -> usize {
        size_of::<FiniteQuotient<D>>()
            .saturating_add(staircase::retained_basis_bytes(&self.source_basis))
            .saturating_add(staircase::retained_staircase_bytes(
                &self.staircase,
                self.ring().nvars(),
            ))
    }

    pub(crate) fn standard_monomials_internal(&self) -> &[Monomial] {
        &self.staircase.monomials
    }

    pub(crate) fn reduce_with_limits(
        &self,
        polynomial: &Polynomial<D>,
        limits: &ComputeLimits,
    ) -> Result<Polynomial<D>, QuotientError> {
        self.reduce_with_extra(polynomial, limits, 0)
    }

    fn reduce_with_extra(
        &self,
        polynomial: &Polynomial<D>,
        limits: &ComputeLimits,
        extra_bytes: usize,
    ) -> Result<Polynomial<D>, QuotientError> {
        self.check_ring(polynomial)?;
        let retained = self.retained_bytes();
        self.check_limits(
            limits,
            retained
                .saturating_add(extra_bytes)
                .saturating_add(polynomial.retained_bytes()),
        )?;
        let division_limits =
            Self::limits_for_division(limits, retained.saturating_add(extra_bytes))?;
        let reduced = normal_form::normal_form(&self.source_basis, polynomial, &division_limits)
            .map_err(QuotientError::from)?;
        self.check_limits(
            limits,
            retained
                .saturating_add(extra_bytes)
                .saturating_add(polynomial.retained_bytes())
                .saturating_add(reduced.retained_bytes()),
        )?;
        Ok(reduced)
    }

    fn limits_for_division(
        limits: &ComputeLimits,
        held: usize,
    ) -> Result<ComputeLimits, QuotientError> {
        let mut division_limits = limits.clone();
        if let Some(limit) = limits.memory {
            if held > limit {
                return Err(QuotientError::MemoryLimitExceeded);
            }
            division_limits.memory = Some(limit - held);
        }
        Ok(division_limits)
    }

    pub(crate) fn multiply_with_limits(
        &self,
        left: &Polynomial<D>,
        right: &Polynomial<D>,
        limits: &ComputeLimits,
    ) -> Result<Polynomial<D>, QuotientError> {
        self.check_ring(left)?;
        self.check_ring(right)?;
        let retained = self.retained_bytes();
        self.check_limits(
            limits,
            retained
                .saturating_add(left.retained_bytes())
                .saturating_add(right.retained_bytes())
                .saturating_add(multiply_estimate_bytes(left, right)),
        )?;
        let product = left
            .try_mul_with_limits(right, limits)
            .map_err(quotient_arithmetic_error)?;
        self.reduce_with_extra(
            &product,
            limits,
            left.retained_bytes().saturating_add(right.retained_bytes()),
        )
    }

    fn monomial_polynomial(&self, monomial: &Monomial) -> Polynomial<D> {
        Polynomial::from_sorted_terms(
            self.ring().clone(),
            vec![Term {
                coeff: self.ring().ops().one(),
                mono: monomial.clone(),
            }],
        )
    }

    fn add_with_limits(
        &self,
        left: &Polynomial<D>,
        right: &Polynomial<D>,
        limits: &ComputeLimits,
    ) -> Result<Polynomial<D>, QuotientError> {
        let retained = self.retained_bytes();
        self.check_limits(
            limits,
            retained
                .saturating_add(left.retained_bytes())
                .saturating_add(right.retained_bytes()),
        )?;
        let sum = left
            .try_add_with_limits(right, limits)
            .map_err(quotient_arithmetic_error)?;
        self.check_limits(limits, retained.saturating_add(sum.retained_bytes()))?;
        self.reduce_with_extra(
            &sum,
            limits,
            left.retained_bytes().saturating_add(right.retained_bytes()),
        )
    }

    fn coordinates_with_limits(
        &self,
        polynomial: &Polynomial<D>,
        limits: &ComputeLimits,
    ) -> Result<CoordinateVector<D>, QuotientError> {
        let reduced = self.reduce_with_limits(polynomial, limits)?;
        self.coordinates_of_reduced(&reduced, limits, polynomial.retained_bytes())
    }

    fn coordinates_of_reduced(
        &self,
        reduced: &Polynomial<D>,
        limits: &ComputeLimits,
        extra_bytes: usize,
    ) -> Result<Vec<Option<D::Coeff>>, QuotientError> {
        let coordinate_bytes = self
            .staircase
            .basis
            .len()
            .saturating_mul(size_of::<Option<D::Coeff>>())
            .saturating_add(reduced.coefficient_bytes());
        self.check_limits(
            limits,
            self.retained_bytes()
                .saturating_add(extra_bytes)
                .saturating_add(reduced.retained_bytes())
                .saturating_add(coordinate_bytes),
        )?;
        let mut coordinates = vec![None; self.staircase.basis.len()];
        for (term_index, (coefficient, exponents)) in reduced.terms().enumerate() {
            if term_index.is_multiple_of(TICK) {
                self.check_limits(
                    limits,
                    self.retained_bytes()
                        .saturating_add(extra_bytes)
                        .saturating_add(reduced.retained_bytes())
                        .saturating_add(coordinate_bytes),
                )?;
            }
            let index = self
                .staircase
                .index
                .get(exponents)
                .copied()
                .unwrap_or_else(|| {
                    unreachable!(
                        "a normal-form term must occur in the completed standard-monomial index"
                    )
                });
            coordinates[index] = Some(coefficient.clone());
        }
        let actual_coordinate_bytes = coordinates
            .capacity()
            .saturating_mul(size_of::<Option<D::Coeff>>())
            .saturating_add(
                coordinates
                    .iter()
                    .filter_map(Option::as_ref)
                    .map(|coefficient| self.ring().ops().heap_bytes(coefficient))
                    .fold(0usize, usize::saturating_add),
            );
        self.check_limits(
            limits,
            self.retained_bytes()
                .saturating_add(extra_bytes)
                .saturating_add(reduced.retained_bytes())
                .saturating_add(actual_coordinate_bytes),
        )?;
        Ok(coordinates)
    }

    fn check_ring(&self, polynomial: &Polynomial<D>) -> Result<(), QuotientError> {
        if polynomial.ring() != self.ring() {
            Err(QuotientError::RingMismatch)
        } else {
            Ok(())
        }
    }

    fn check_limits(&self, limits: &ComputeLimits, bytes: usize) -> Result<(), QuotientError> {
        if let Some(stop) = limits.stop() {
            return Err(QuotientError::from(stop));
        }
        if limits.memory.is_some_and(|limit| bytes > limit) {
            return Err(QuotientError::MemoryLimitExceeded);
        }
        Ok(())
    }
}

impl<D: Domain> GroebnerBasis<D> {
    /// Report whether the quotient by this basis has finite vector-space
    /// dimension.
    ///
    /// The test checks the pure-power criterion on the leading monomial
    /// ideal. The unit ideal returns `true` because its quotient is the zero
    /// algebra. A zero-variable zero ideal also returns `true` and has
    /// dimension one. A zero ideal with variables returns `false`.
    pub fn is_zero_dimensional(&self) -> bool {
        staircase::zero_dimensional(self)
    }

    /// Build the finite quotient algebra defined by this basis.
    ///
    /// The source basis is cloned, including its domain metadata. The
    /// staircase walk is complete when every variable has a pure power in
    /// the leading ideal. A positive-dimensional leading ideal returns
    /// [`QuotientError::NotFinite`]. The unit ideal returns the zero
    /// algebra. The budget covers the retained clone and every staircase
    /// allocation.
    pub fn finite_quotient(&self, budget: Budget) -> Result<FiniteQuotient<D>, QuotientError> {
        let limits = ComputeLimits::of_budget(&budget);
        let retained = staircase::retained_basis_bytes(self);
        if let Some(stop) = limits.stop() {
            return Err(QuotientError::from(stop));
        }
        if limits
            .memory
            .is_some_and(|limit| retained.saturating_add(size_of::<FiniteQuotient<D>>()) > limit)
        {
            return Err(QuotientError::MemoryLimitExceeded);
        }
        let source_basis = self.clone();
        let staircase = staircase::build(&source_basis, &limits)?;
        Ok(FiniteQuotient {
            source_basis,
            staircase,
        })
    }
}

fn multiply_estimate_bytes<D: Domain>(left: &Polynomial<D>, right: &Polynomial<D>) -> usize {
    let pair_count = left.terms.len().saturating_mul(right.terms.len());
    pair_count
        .saturating_mul(size_of::<Term<D>>().saturating_add(heap_exps_bytes(left.ring().nvars())))
        .saturating_add(left.coefficient_bytes().saturating_mul(right.terms.len()))
        .saturating_add(right.coefficient_bytes().saturating_mul(left.terms.len()))
}

impl From<RunError> for QuotientError {
    fn from(error: RunError) -> Self {
        quotient_run_error(error)
    }
}
