//! Exact ideal equality checks over the rationals.
//!
//! The check is deliberately separate from the multimodular engine. It
//! validates the candidate basis, checks the reverse inclusion, computes a
//! tracked exact Buchberger basis of the input, and checks the forward
//! identities by exact multiplication.

use std::cmp::Ordering;
use std::collections::BinaryHeap;
use std::fmt;
use std::mem::size_of;

use num_rational::BigRational;
use num_traits::One;

use crate::arithmetic::ArithmeticError;
use crate::compute::{Budget, ComputeError, ComputeLimits, DEGREE_LIMIT, RunError};
use crate::ideal::{GroebnerBasis, Ideal};
use crate::normal_form::{self, BasisError, DivisionStop};
use crate::poly::{Monomial, Polynomial, Term, heap_exps_bytes};
use crate::ring::{DomainOps, PolynomialRing, Rationals};

/// The result of an exact rational ideal equality check.
///
/// `origins()[j][i]` is the cofactor `h_ji` in
/// `g_j = sum_i h_ji f_i`. The result exists only after the candidate
/// checks, both containments, and every exact multiplication check pass.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RationalEqualityCheck {
    input: Ideal<Rationals>,
    basis: GroebnerBasis<Rationals>,
    origins: Vec<Vec<Polynomial<Rationals>>>,
    metrics: RationalEqualityMetrics,
}

impl RationalEqualityCheck {
    /// Return the exact input ideal associated with this check.
    pub fn input(&self) -> &Ideal<Rationals> {
        &self.input
    }

    /// Return the exact candidate basis associated with this check.
    pub fn basis(&self) -> &GroebnerBasis<Rationals> {
        &self.basis
    }

    /// Return the exact cofactor matrix in candidate and generator order.
    pub fn origins(&self) -> &[Vec<Polynomial<Rationals>>] {
        &self.origins
    }

    /// Return counters from the exact check.
    pub fn metrics(&self) -> RationalEqualityMetrics {
        self.metrics
    }
}

/// Counters from a successful exact rational ideal equality check.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RationalEqualityMetrics {
    /// The number of elements in the tracked raw Buchberger basis.
    pub raw_basis_elements: usize,
    /// The number of terms in the tracked raw Buchberger basis.
    pub raw_basis_terms: usize,
    /// Estimated live data immediately before the temporary exact basis is dropped.
    /// The estimate excludes the retained input and basis clones in the result.
    pub final_working_bytes: usize,
}

/// Why an exact rational equality check stopped or rejected its arguments.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EqualityCheckError {
    /// A polynomial belongs to another ring.
    RingMismatch,
    /// The candidate is not a reduced Gröbner basis.
    Candidate(BasisError),
    /// A generator has a nonzero remainder by the candidate basis.
    ReverseMembership {
        /// The generator index.
        generator: usize,
    },
    /// A candidate element has a nonzero remainder by the exact input basis.
    ForwardMembership {
        /// The candidate element index.
        basis: usize,
    },
    /// A product needs an exponent above `limit`.
    ExponentLimit {
        /// The largest exponent one monomial can hold.
        limit: u32,
    },
    /// The deadline passed.
    Timeout,
    /// The tracked live data passed the memory limit.
    MemoryLimitExceeded,
}

impl fmt::Display for EqualityCheckError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EqualityCheckError::RingMismatch => f.write_str("a polynomial belongs to another ring"),
            EqualityCheckError::Candidate(error) => {
                write!(f, "the candidate basis failed: {error}")
            }
            EqualityCheckError::ReverseMembership { generator } => {
                write!(f, "generator {generator} is outside the candidate ideal")
            }
            EqualityCheckError::ForwardMembership { basis } => {
                write!(f, "basis element {basis} is outside the input ideal")
            }
            EqualityCheckError::ExponentLimit { limit } => {
                write!(f, "the equality check reached an exponent above {limit}")
            }
            EqualityCheckError::Timeout => f.write_str("the equality check passed its deadline"),
            EqualityCheckError::MemoryLimitExceeded => {
                f.write_str("the equality check passed its memory limit")
            }
        }
    }
}

impl std::error::Error for EqualityCheckError {}

/// Check exact equality between the ideal generated by `generators` and
/// `basis`.
pub(crate) fn check_basis(
    ring: &PolynomialRing<Rationals>,
    generators: &[Polynomial<Rationals>],
    basis: &GroebnerBasis<Rationals>,
    budget: Budget,
) -> Result<RationalEqualityCheck, EqualityCheckError> {
    let limits = ComputeLimits::of_budget(&budget);
    check_basis_with_limits(ring, generators, basis, &limits, 0)
}

/// Check exact equality under absolute limits shared with a larger call.
pub(crate) fn check_basis_with_limits(
    ring: &PolynomialRing<Rationals>,
    generators: &[Polynomial<Rationals>],
    basis: &GroebnerBasis<Rationals>,
    limits: &ComputeLimits,
    external_bytes: usize,
) -> Result<RationalEqualityCheck, EqualityCheckError> {
    let sizes = input_sizes(ring, generators, basis, limits, external_bytes)?;
    let candidate: &[Polynomial<Rationals>] = basis;
    let (raw, origin_matrix) = check_phases(ring, generators, candidate, limits, &sizes)?;
    finish_result(ring, generators, basis, raw, origin_matrix, limits, &sizes)
}

struct InputSizes {
    external_bytes: usize,
    candidate_bytes: usize,
    input_and_candidate_bytes: usize,
    held: usize,
}

fn input_sizes(
    ring: &PolynomialRing<Rationals>,
    generators: &[Polynomial<Rationals>],
    basis: &GroebnerBasis<Rationals>,
    limits: &ComputeLimits,
    external_bytes: usize,
) -> Result<InputSizes, EqualityCheckError> {
    if basis.ring() != ring || generators.iter().any(|poly| poly.ring() != ring) {
        return Err(EqualityCheckError::RingMismatch);
    }
    let input_bytes = polys_bytes(generators);
    let candidate_bytes = polys_bytes(basis);
    let input_and_candidate_bytes = input_bytes.saturating_add(candidate_bytes);
    let held = external_bytes.saturating_add(input_and_candidate_bytes);
    check_limits(limits, held)?;
    Ok(InputSizes {
        external_bytes,
        candidate_bytes,
        input_and_candidate_bytes,
        held,
    })
}

fn check_phases(
    ring: &PolynomialRing<Rationals>,
    generators: &[Polynomial<Rationals>],
    candidate: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
    sizes: &InputSizes,
) -> Result<(RawBasis, Vec<Origin>), EqualityCheckError> {
    check_candidate(ring, candidate, limits, sizes.held)?;
    check_reverse_inclusion(generators, candidate, limits, sizes.held)?;
    let raw_limits = residual_limits(
        limits,
        sizes.external_bytes.saturating_add(sizes.candidate_bytes),
    )?;
    let (raw, origins) = tracked_basis(ring, generators, &raw_limits)?;
    let raw_bytes = polys_vec_bytes(&raw).saturating_add(origins_vec_bytes(&origins));
    let origin_matrix = forward_origins(
        candidate,
        &raw,
        &origins,
        generators,
        limits,
        sizes.held.saturating_add(raw_bytes),
    )?;
    Ok((
        RawBasis {
            polynomials: raw,
            origins,
            bytes: raw_bytes,
        },
        origin_matrix,
    ))
}

fn finish_result(
    ring: &PolynomialRing<Rationals>,
    generators: &[Polynomial<Rationals>],
    basis: &GroebnerBasis<Rationals>,
    raw: RawBasis,
    origin_matrix: Vec<Origin>,
    limits: &ComputeLimits,
    sizes: &InputSizes,
) -> Result<RationalEqualityCheck, EqualityCheckError> {
    let recomputed_raw_bytes =
        polys_vec_bytes(&raw.polynomials).saturating_add(origins_vec_bytes(&raw.origins));
    debug_assert_eq!(raw.bytes, recomputed_raw_bytes);
    let working_bytes = sizes
        .held
        .saturating_add(raw.bytes)
        .saturating_add(origins_vec_bytes(&origin_matrix));
    let result_bytes = working_bytes.saturating_add(sizes.input_and_candidate_bytes);
    check_limits(limits, result_bytes)?;
    let input = Ideal::new(ring.clone(), generators.to_vec());
    let stored_basis = basis.clone();
    let metrics = RationalEqualityMetrics {
        raw_basis_elements: raw.polynomials.len(),
        raw_basis_terms: raw.polynomials.iter().map(|poly| poly.terms.len()).sum(),
        final_working_bytes: working_bytes,
    };
    let result = RationalEqualityCheck {
        input,
        basis: stored_basis,
        origins: origin_matrix,
        metrics,
    };
    check_limits(limits, result_bytes)?;
    Ok(result)
}

fn check_candidate(
    ring: &PolynomialRing<Rationals>,
    candidate: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
    external_bytes: usize,
) -> Result<(), EqualityCheckError> {
    let local = residual_limits(limits, external_bytes)?;
    normal_form::check_basis(ring, candidate, &local).map_err(map_candidate_error)
}

fn check_reverse_inclusion(
    generators: &[Polynomial<Rationals>],
    candidate: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
    external_bytes: usize,
) -> Result<(), EqualityCheckError> {
    for (index, generator) in generators.iter().enumerate() {
        let local = residual_limits(limits, external_bytes)?;
        let remainder =
            normal_form::normal_form(candidate, generator, &local).map_err(map_division_error)?;
        if !remainder.is_zero() {
            return Err(EqualityCheckError::ReverseMembership { generator: index });
        }
    }
    Ok(())
}

type Origin = Vec<Polynomial<Rationals>>;
struct RawBasis {
    polynomials: Vec<Polynomial<Rationals>>,
    origins: Vec<Origin>,
    bytes: usize,
}

struct TrackedState<'a> {
    ring: &'a PolynomialRing<Rationals>,
    generators: &'a [Polynomial<Rationals>],
    limits: &'a ComputeLimits,
    basis: Vec<Polynomial<Rationals>>,
    origins: Vec<Origin>,
    pairs: BinaryHeap<std::cmp::Reverse<Pair>>,
}

impl TrackedState<'_> {
    fn bytes(&self) -> usize {
        state_bytes(
            self.generators,
            &self.basis,
            &self.origins,
            &self.pairs,
            &[],
        )
    }
}

fn tracked_basis(
    ring: &PolynomialRing<Rationals>,
    generators: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
) -> Result<(Vec<Polynomial<Rationals>>, Vec<Origin>), EqualityCheckError> {
    let mut state = TrackedState {
        ring,
        generators,
        limits,
        basis: Vec::new(),
        origins: Vec::new(),
        pairs: BinaryHeap::new(),
    };
    for index in 0..generators.len() {
        append_generator(&mut state, index)?;
    }
    while let Some(std::cmp::Reverse(pair)) = state.pairs.pop() {
        append_pair(&mut state, pair)?;
    }
    Ok((state.basis, state.origins))
}

fn append_generator(state: &mut TrackedState<'_>, index: usize) -> Result<(), EqualityCheckError> {
    check_limits(state.limits, state.bytes())?;
    let generator = &state.generators[index];
    let Some(leading_term) = generator.leading_term() else {
        return Ok(());
    };
    let coefficient_bytes = state.ring.ops().heap_bytes(leading_term.0);
    let held = state.bytes();
    check_limits(state.limits, held.saturating_add(coefficient_bytes))?;
    let leading_coefficient = leading_term.0.clone();
    let (monic, inverse) = monic_with_inverse(
        generator,
        &leading_coefficient,
        state.limits,
        held.saturating_add(coefficient_bytes),
    )?;
    let inverse_bytes = inverse
        .as_ref()
        .map_or(0, |coefficient| state.ring.ops().heap_bytes(coefficient));
    let mut origin = unit_origin(
        state.ring,
        index,
        state.generators.len(),
        state.limits,
        held.saturating_add(monic.retained_bytes())
            .saturating_add(inverse_bytes),
    )?;
    if let Some(inverse) = inverse {
        scale_origin(
            &mut origin,
            &inverse,
            state.limits,
            held.saturating_add(monic.retained_bytes())
                .saturating_add(inverse_bytes),
        )?;
    }
    append_element(state, monic, origin)
}

fn append_pair(state: &mut TrackedState<'_>, pair: Pair) -> Result<(), EqualityCheckError> {
    check_limits(state.limits, state.bytes())?;
    let held = state.bytes();
    let (spoly, spoly_origin) = s_polynomial_tracked(
        &state.basis,
        &state.origins,
        pair.left,
        pair.right,
        state.limits,
        held,
    )?;
    let target_held = held
        .saturating_add(spoly.retained_bytes())
        .saturating_add(origin_vec_bytes(&spoly_origin));
    let (remainder, mut remainder_origin) = normal_form_tracked(
        &spoly,
        &spoly_origin,
        &state.basis,
        &state.origins,
        state.limits,
        target_held,
    )?;
    if remainder.is_zero() {
        return Ok(());
    }
    let Some(leading_term) = remainder.leading_term() else {
        return Ok(());
    };
    let coefficient_bytes = state.ring.ops().heap_bytes(leading_term.0);
    let held = state
        .bytes()
        .saturating_add(remainder.retained_bytes())
        .saturating_add(origin_vec_bytes(&remainder_origin));
    check_limits(state.limits, held.saturating_add(coefficient_bytes))?;
    let leading_coefficient = leading_term.0.clone();
    let (monic, inverse) = monic_with_inverse(
        &remainder,
        &leading_coefficient,
        state.limits,
        held.saturating_add(coefficient_bytes),
    )?;
    if let Some(inverse) = inverse {
        let inverse_bytes = state.ring.ops().heap_bytes(&inverse);
        scale_origin(
            &mut remainder_origin,
            &inverse,
            state.limits,
            held.saturating_add(inverse_bytes),
        )?;
    }
    append_element(state, monic, remainder_origin)
}

fn append_element(
    state: &mut TrackedState<'_>,
    polynomial: Polynomial<Rationals>,
    origin: Origin,
) -> Result<(), EqualityCheckError> {
    let held = state
        .bytes()
        .saturating_add(polynomial.retained_bytes())
        .saturating_add(origin_vec_bytes(&origin));
    reserve_vec_slots(&mut state.basis, 1, held, state.limits)?;
    reserve_vec_slots(&mut state.origins, 1, held, state.limits)?;
    state.basis.push(polynomial);
    state.origins.push(origin);
    add_pairs(state, state.basis.len() - 1)
}

fn unit_origin(
    ring: &PolynomialRing<Rationals>,
    index: usize,
    count: usize,
    limits: &ComputeLimits,
    held: usize,
) -> Result<Origin, EqualityCheckError> {
    let vector_bytes = size_of::<Origin>()
        .saturating_add(size_of::<Polynomial<Rationals>>().saturating_mul(count));
    let one_bytes = size_of::<Term<Rationals>>()
        .saturating_add(heap_exps_bytes(ring.nvars()))
        .saturating_add(ring.ops().heap_bytes(&BigRational::one()));
    check_limits(
        limits,
        held.saturating_add(vector_bytes).saturating_add(one_bytes),
    )?;
    let mut origin = vec![ring.zero(); count];
    origin[index] = ring.one();
    check_limits(limits, held.saturating_add(origin_vec_bytes(&origin)))?;
    Ok(origin)
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct Pair {
    degree: u32,
    left: usize,
    right: usize,
}

impl Ord for Pair {
    fn cmp(&self, other: &Self) -> Ordering {
        self.degree
            .cmp(&other.degree)
            .then_with(|| self.left.cmp(&other.left))
            .then_with(|| self.right.cmp(&other.right))
    }
}

impl PartialOrd for Pair {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

fn add_pairs(state: &mut TrackedState<'_>, index: usize) -> Result<(), EqualityCheckError> {
    for other in 0..index {
        if let Some(stop) = state.limits.stop_every(other) {
            return Err(map_run_error(stop));
        }
        let degree = {
            let left_lm = leading_monomial(&state.basis[other]);
            let right_lm = leading_monomial(&state.basis[index]);
            if left_lm.is_coprime(right_lm) {
                None
            } else {
                Some(
                    left_lm
                        .exps
                        .iter()
                        .zip(&right_lm.exps)
                        .map(|(&left, &right)| u32::from(left.max(right)))
                        .sum(),
                )
            }
        };
        let Some(degree) = degree else { continue };
        let held = state.bytes();
        reserve_heap_slot(&mut state.pairs, held, state.limits)?;
        state.pairs.push(std::cmp::Reverse(Pair {
            degree,
            left: other,
            right: index,
        }));
    }
    Ok(())
}

fn s_polynomial_tracked(
    basis: &[Polynomial<Rationals>],
    origins: &[Origin],
    left: usize,
    right: usize,
    limits: &ComputeLimits,
    held: usize,
) -> Result<(Polynomial<Rationals>, Origin), EqualityCheckError> {
    let left_term = basis[left]
        .leading_term()
        .expect("the left basis element is nonzero");
    let right_term = basis[right]
        .leading_term()
        .expect("the right basis element is nonzero");
    let (left_shift, right_shift) =
        lcm_shifts_with_limits(left_term.1, right_term.1, limits, held)?;
    let shift_bytes = size_of::<u16>()
        .saturating_mul(left_shift.capacity().saturating_add(right_shift.capacity()));
    let left_scaled = scale_shifted(
        &basis[left],
        right_term.0,
        &left_shift,
        limits,
        held.saturating_add(shift_bytes),
    )?;
    let right_held = held
        .saturating_add(shift_bytes)
        .saturating_add(left_scaled.retained_bytes());
    let right_scaled = scale_shifted(&basis[right], left_term.0, &right_shift, limits, right_held)?;
    let polynomial_held = right_held.saturating_add(right_scaled.retained_bytes());
    let polynomial = subtract(&left_scaled, &right_scaled, limits, polynomial_held)?;
    let origin_slots = size_of::<Origin>()
        .saturating_add(size_of::<Polynomial<Rationals>>().saturating_mul(origins[left].len()));
    let origin_held = polynomial_held
        .saturating_add(polynomial.retained_bytes())
        .saturating_add(origin_slots);
    check_limits(limits, origin_held)?;
    let mut origin = Vec::with_capacity(origins[left].len());
    for (left_origin, right_origin) in origins[left].iter().zip(&origins[right]) {
        let row_held = origin_held.saturating_add(origin_vec_bytes(&origin));
        let left_scaled = scale_shifted(left_origin, right_term.0, &left_shift, limits, row_held)?;
        let right_held = row_held.saturating_add(left_scaled.retained_bytes());
        let right_scaled =
            scale_shifted(right_origin, left_term.0, &right_shift, limits, right_held)?;
        let cell_held = right_held.saturating_add(right_scaled.retained_bytes());
        let cell = subtract(&left_scaled, &right_scaled, limits, cell_held)?;
        origin.push(cell);
    }
    Ok((polynomial, origin))
}

struct TrackedNormalForm {
    work: Polynomial<Rationals>,
    origin: Origin,
    remainder: Polynomial<Rationals>,
}

struct TrackedReduction<'a> {
    basis: &'a [Polynomial<Rationals>],
    basis_origins: &'a [Origin],
    limits: &'a ComputeLimits,
    base_held: usize,
}

fn normal_form_tracked(
    target: &Polynomial<Rationals>,
    target_origin: &Origin,
    basis: &[Polynomial<Rationals>],
    basis_origins: &[Origin],
    limits: &ComputeLimits,
    held: usize,
) -> Result<(Polynomial<Rationals>, Origin), EqualityCheckError> {
    let initial = held
        .saturating_add(target.retained_bytes())
        .saturating_add(origin_vec_bytes(target_origin));
    check_limits(limits, initial)?;
    let mut state = TrackedNormalForm {
        work: target.clone(),
        origin: target_origin.clone(),
        remainder: target.ring().zero(),
    };
    loop {
        let state_held = tracked_normal_form_bytes(held, &state);
        check_limits(limits, state_held)?;
        let Some((mono, coefficient)) = leading_data(&state.work, state_held, limits)? else {
            break;
        };
        let Some(index) = first_reducer(&mono, basis, limits)? else {
            move_lt_to_remainder(&mut state.work, &mut state.remainder, state_held, limits)?;
            continue;
        };
        let reduction = TrackedReduction {
            basis,
            basis_origins,
            limits,
            base_held: held,
        };
        reduce_tracked_step(&mut state, &reduction, index, &mono, &coefficient)?;
    }
    Ok((state.remainder, state.origin))
}

fn tracked_normal_form_bytes(held: usize, state: &TrackedNormalForm) -> usize {
    held.saturating_add(state.work.retained_bytes())
        .saturating_add(state.remainder.retained_bytes())
        .saturating_add(origin_vec_bytes(&state.origin))
}

fn reduce_tracked_step(
    state: &mut TrackedNormalForm,
    reduction: &TrackedReduction<'_>,
    index: usize,
    mono: &[u16],
    coefficient: &BigRational,
) -> Result<(), EqualityCheckError> {
    let reducer_term = reduction.basis[index]
        .leading_term()
        .expect("the selected reducer is nonzero");
    let data_bytes = copy_data_bytes(state.work.ring(), mono, coefficient);
    let state_held =
        tracked_normal_form_bytes(reduction.base_held, state).saturating_add(data_bytes);
    let shift = quotient_with_limits(mono, reducer_term.1, reduction.limits, state_held)?;
    let shift_bytes = size_of::<u16>().saturating_mul(shift.capacity());
    let scale = divide_coefficient(
        state.work.ring(),
        coefficient,
        reducer_term.0,
        reduction.limits,
        state_held.saturating_add(shift_bytes),
    )?;
    let scale_bytes = state.work.ring().ops().heap_bytes(&scale);
    let product_held = state_held
        .saturating_add(shift_bytes)
        .saturating_add(scale_bytes);
    let product = scale_shifted(
        &reduction.basis[index],
        &scale,
        &shift,
        reduction.limits,
        product_held,
    )?;
    let work_held = product_held.saturating_add(product.retained_bytes());
    state.work = subtract(&state.work, &product, reduction.limits, work_held)?;
    for (row, source) in reduction.basis_origins[index].iter().enumerate() {
        let row_held = tracked_normal_form_bytes(reduction.base_held, state)
            .saturating_add(data_bytes)
            .saturating_add(shift_bytes)
            .saturating_add(scale_bytes);
        let product = scale_shifted(source, &scale, &shift, reduction.limits, row_held)?;
        let cell_held = row_held.saturating_add(product.retained_bytes());
        state.origin[row] = subtract(&state.origin[row], &product, reduction.limits, cell_held)?;
    }
    Ok(())
}

fn move_lt_to_remainder(
    work: &mut Polynomial<Rationals>,
    remainder: &mut Polynomial<Rationals>,
    held: usize,
    limits: &ComputeLimits,
) -> Result<(), EqualityCheckError> {
    reserve_vec_slots(&mut remainder.terms, 1, held, limits)?;
    let term = work
        .pop_lt()
        .expect("the leading term exists while the work is nonzero");
    let ops = *remainder.ring().ops();
    remainder.push_term(term, &ops);
    Ok(())
}

fn leading_data(
    polynomial: &Polynomial<Rationals>,
    held: usize,
    limits: &ComputeLimits,
) -> Result<Option<(Vec<u16>, BigRational)>, EqualityCheckError> {
    let Some(term) = polynomial.lt() else {
        return Ok(None);
    };
    let data_bytes = copy_data_bytes(polynomial.ring(), &term.mono.exps, &term.coeff);
    check_limits(limits, held.saturating_add(data_bytes))?;
    Ok(Some((term.mono.exps.to_vec(), term.coeff.clone())))
}

fn forward_origins(
    candidate: &[Polynomial<Rationals>],
    raw: &[Polynomial<Rationals>],
    raw_origins: &[Origin],
    generators: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
    held: usize,
) -> Result<Vec<Origin>, EqualityCheckError> {
    let out_slots = size_of::<Vec<Origin>>()
        .saturating_add(size_of::<Origin>().saturating_mul(candidate.len()));
    check_limits(limits, held.saturating_add(out_slots))?;
    let mut out = Vec::with_capacity(candidate.len());
    for (index, target) in candidate.iter().enumerate() {
        let out_held = held.saturating_add(origins_vec_bytes(&out));
        check_limits(limits, out_held)?;
        let (quotients, remainder) = divide_with_quotients(target, raw, limits, out_held)?;
        let division_held = out_held
            .saturating_add(polys_vec_bytes(&quotients))
            .saturating_add(remainder.retained_bytes());
        if !remainder.is_zero() {
            return Err(EqualityCheckError::ForwardMembership { basis: index });
        }
        let identity =
            combine_quotients(&quotients, raw_origins, generators, limits, division_held)?;
        let identity_held = division_held
            .saturating_add(origin_vec_bytes(&identity))
            .saturating_add(origins_vec_bytes(&out));
        if !identity_holds(&identity, target, generators, limits, identity_held)? {
            return Err(EqualityCheckError::ForwardMembership { basis: index });
        }
        check_limits(
            limits,
            division_held
                .saturating_add(origins_vec_bytes(&out))
                .saturating_add(origin_vec_bytes(&identity)),
        )?;
        out.push(identity);
    }
    Ok(out)
}

fn divide_with_quotients(
    target: &Polynomial<Rationals>,
    basis: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
    held: usize,
) -> Result<(Vec<Polynomial<Rationals>>, Polynomial<Rationals>), EqualityCheckError> {
    let quotient_slots = size_of::<Vec<Polynomial<Rationals>>>()
        .saturating_add(size_of::<Polynomial<Rationals>>().saturating_mul(basis.len()));
    check_limits(
        limits,
        held.saturating_add(target.retained_bytes())
            .saturating_add(quotient_slots),
    )?;
    let quotients = vec![target.ring().zero(); basis.len()];
    check_limits(
        limits,
        held.saturating_add(target.retained_bytes())
            .saturating_add(polys_vec_bytes(&quotients)),
    )?;
    check_limits(
        limits,
        held.saturating_add(target.retained_bytes())
            .saturating_add(polys_vec_bytes(&quotients))
            .saturating_add(target.retained_bytes()),
    )?;
    let mut state = DivisionState {
        target,
        basis,
        limits,
        held,
        quotients,
        work: target.clone(),
        remainder: target.ring().zero(),
    };
    check_limits(limits, state.bytes())?;
    while state.work.lt().is_some() {
        let state_held = state.bytes();
        let Some((mono, coefficient)) = leading_data(&state.work, state_held, limits)? else {
            break;
        };
        let Some(index) = first_reducer(&mono, basis, limits)? else {
            move_lt_to_remainder(&mut state.work, &mut state.remainder, state_held, limits)?;
            continue;
        };
        divide_step(&mut state, index, &mono, &coefficient)?;
    }
    Ok((state.quotients, state.remainder))
}

struct DivisionState<'a> {
    target: &'a Polynomial<Rationals>,
    basis: &'a [Polynomial<Rationals>],
    limits: &'a ComputeLimits,
    held: usize,
    quotients: Vec<Polynomial<Rationals>>,
    work: Polynomial<Rationals>,
    remainder: Polynomial<Rationals>,
}

impl DivisionState<'_> {
    fn bytes(&self) -> usize {
        self.held
            .saturating_add(self.target.retained_bytes())
            .saturating_add(polys_vec_bytes(&self.quotients))
            .saturating_add(self.work.retained_bytes())
            .saturating_add(self.remainder.retained_bytes())
    }
}

fn divide_step(
    state: &mut DivisionState<'_>,
    index: usize,
    mono: &[u16],
    coefficient: &BigRational,
) -> Result<(), EqualityCheckError> {
    let reducer_term = state.basis[index]
        .leading_term()
        .expect("the selected reducer is nonzero");
    let data_bytes = copy_data_bytes(state.work.ring(), mono, coefficient);
    let state_held = state.bytes().saturating_add(data_bytes);
    let shift = quotient_with_limits(mono, reducer_term.1, state.limits, state_held)?;
    let shift_bytes = size_of::<u16>().saturating_mul(shift.capacity());
    let scale = divide_coefficient(
        state.work.ring(),
        coefficient,
        reducer_term.0,
        state.limits,
        state_held.saturating_add(shift_bytes),
    )?;
    let scale_bytes = state.work.ring().ops().heap_bytes(&scale);
    let term_held = state_held
        .saturating_add(shift_bytes)
        .saturating_add(scale_bytes);
    let term = monomial_multiplier(state.work.ring(), &scale, &shift, state.limits, term_held)?;
    let quotient_held = term_held.saturating_add(term.retained_bytes());
    state.quotients[index] = add(&state.quotients[index], &term, state.limits, quotient_held)?;
    let product_held = state
        .bytes()
        .saturating_add(data_bytes)
        .saturating_add(shift_bytes)
        .saturating_add(scale_bytes)
        .saturating_add(term.retained_bytes());
    let product = multiply(&state.basis[index], &term, state.limits, product_held)?;
    state.work = subtract(
        &state.work,
        &product,
        state.limits,
        product_held.saturating_add(product.retained_bytes()),
    )?;
    Ok(())
}

fn combine_quotients(
    quotients: &[Polynomial<Rationals>],
    raw_origins: &[Origin],
    generators: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
    held: usize,
) -> Result<Origin, EqualityCheckError> {
    let ring = generators
        .first()
        .map(Polynomial::ring)
        .or_else(|| quotients.first().map(Polynomial::ring))
        .ok_or(EqualityCheckError::RingMismatch)?;
    let slots = size_of::<Origin>()
        .saturating_add(size_of::<Polynomial<Rationals>>().saturating_mul(generators.len()));
    check_limits(limits, held.saturating_add(slots))?;
    let mut result = vec![ring.zero(); generators.len()];
    check_limits(limits, held.saturating_add(origin_vec_bytes(&result)))?;
    for (quotient, origin) in quotients.iter().zip(raw_origins) {
        let result_held = held.saturating_add(origin_vec_bytes(&result));
        for (slot, raw_cofactor) in result.iter_mut().zip(origin) {
            let product = multiply(quotient, raw_cofactor, limits, result_held)?;
            *slot = add(
                slot,
                &product,
                limits,
                result_held.saturating_add(product.retained_bytes()),
            )?;
        }
        check_limits(limits, held.saturating_add(origin_vec_bytes(&result)))?;
    }
    Ok(result)
}

fn identity_holds(
    identity: &Origin,
    target: &Polynomial<Rationals>,
    generators: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
    held: usize,
) -> Result<bool, EqualityCheckError> {
    let mut sum = target.ring().zero();
    for (cofactor, generator) in identity.iter().zip(generators) {
        let sum_held = held.saturating_add(sum.retained_bytes());
        let product = multiply(cofactor, generator, limits, sum_held)?;
        sum = add(
            &sum,
            &product,
            limits,
            sum_held.saturating_add(product.retained_bytes()),
        )?;
    }
    Ok(sum == *target)
}

fn first_reducer(
    mono: &[u16],
    basis: &[Polynomial<Rationals>],
    limits: &ComputeLimits,
) -> Result<Option<usize>, EqualityCheckError> {
    for (index, poly) in basis.iter().enumerate() {
        if let Some(stop) = limits.stop_every(index) {
            return Err(map_run_error(stop));
        }
        if poly
            .leading_term()
            .is_some_and(|(_, exponents)| divides(exponents, mono))
        {
            return Ok(Some(index));
        }
    }
    Ok(None)
}

fn monic_with_inverse(
    poly: &Polynomial<Rationals>,
    leading_coefficient: &BigRational,
    limits: &ComputeLimits,
    held: usize,
) -> Result<(Polynomial<Rationals>, Option<BigRational>), EqualityCheckError> {
    if leading_coefficient.is_one() {
        check_limits(limits, held.saturating_add(poly.retained_bytes()))?;
        return Ok((poly.clone(), None));
    }
    let inverse = reciprocal(poly, leading_coefficient, limits, held)?;
    let inverse_bytes = poly.ring().ops().heap_bytes(&inverse);
    let monic = scale_poly(poly, &inverse, limits, held.saturating_add(inverse_bytes))?;
    Ok((monic, Some(inverse)))
}

fn reciprocal(
    poly: &Polynomial<Rationals>,
    coefficient: &BigRational,
    limits: &ComputeLimits,
    held: usize,
) -> Result<BigRational, EqualityCheckError> {
    let bytes = poly.ring().ops().heap_bytes(coefficient);
    check_limits(limits, held.saturating_add(bytes))?;
    let inverse = coefficient.recip();
    check_limits(
        limits,
        held.saturating_add(bytes)
            .saturating_add(poly.ring().ops().heap_bytes(&inverse)),
    )?;
    Ok(inverse)
}

fn divide_coefficient(
    ring: &PolynomialRing<Rationals>,
    numerator: &BigRational,
    denominator: &BigRational,
    limits: &ComputeLimits,
    held: usize,
) -> Result<BigRational, EqualityCheckError> {
    let bound = ring
        .ops()
        .heap_bytes(numerator)
        .saturating_add(ring.ops().heap_bytes(denominator));
    check_limits(limits, held.saturating_add(bound))?;
    let quotient =
        crate::poly::divide_coefficients::<Rationals>(ring.ops(), numerator, denominator);
    check_limits(
        limits,
        held.saturating_add(bound)
            .saturating_add(ring.ops().heap_bytes(&quotient)),
    )?;
    Ok(quotient)
}

fn scale_origin(
    origin: &mut Origin,
    coefficient: &BigRational,
    limits: &ComputeLimits,
    held: usize,
) -> Result<(), EqualityCheckError> {
    for index in 0..origin.len() {
        let row_held = held
            .saturating_add(origin_vec_bytes(origin))
            .saturating_add(origin[index].ring().ops().heap_bytes(coefficient));
        origin[index] = scale_poly(&origin[index], coefficient, limits, row_held)?;
    }
    Ok(())
}

fn scale_poly(
    poly: &Polynomial<Rationals>,
    coefficient: &BigRational,
    limits: &ComputeLimits,
    held: usize,
) -> Result<Polynomial<Rationals>, EqualityCheckError> {
    let coefficient_bytes = poly.ring().ops().heap_bytes(coefficient);
    check_limits(limits, held.saturating_add(coefficient_bytes))?;
    let local = operation_limits(limits, held)?;
    poly.try_scale_with_limits(coefficient.clone(), &local)
        .map_err(EqualityCheckError::from)
}

fn scale_shifted(
    poly: &Polynomial<Rationals>,
    coefficient: &BigRational,
    shift: &[u16],
    limits: &ComputeLimits,
    held: usize,
) -> Result<Polynomial<Rationals>, EqualityCheckError> {
    let multiplier = monomial_multiplier(poly.ring(), coefficient, shift, limits, held)?;
    multiply(
        poly,
        &multiplier,
        limits,
        held.saturating_add(multiplier.retained_bytes()),
    )
}

fn monomial_multiplier(
    ring: &PolynomialRing<Rationals>,
    coefficient: &BigRational,
    shift: &[u16],
    limits: &ComputeLimits,
    held: usize,
) -> Result<Polynomial<Rationals>, EqualityCheckError> {
    if shift.len() != ring.nvars() {
        return Err(EqualityCheckError::RingMismatch);
    }
    let term_bytes = size_of::<Term<Rationals>>()
        .saturating_add(size_of::<u16>().saturating_mul(shift.len()))
        .saturating_add(ring.ops().heap_bytes(coefficient));
    check_limits(limits, held.saturating_add(term_bytes))?;
    ring.polynomial([(coefficient.clone(), shift.to_vec())])
        .map_err(|_| EqualityCheckError::RingMismatch)
}

fn multiply(
    left: &Polynomial<Rationals>,
    right: &Polynomial<Rationals>,
    limits: &ComputeLimits,
    held: usize,
) -> Result<Polynomial<Rationals>, EqualityCheckError> {
    if left.ring() != right.ring() {
        return Err(EqualityCheckError::RingMismatch);
    }
    let operands = left.retained_bytes().saturating_add(right.retained_bytes());
    let local = operation_limits(limits, held)?;
    left.try_mul_with_limits(right, &local)
        .map_err(EqualityCheckError::from)
        .and_then(|product| {
            check_limits(
                limits,
                held.saturating_add(operands)
                    .saturating_add(product.retained_bytes()),
            )?;
            Ok(product)
        })
}

fn subtract(
    left: &Polynomial<Rationals>,
    right: &Polynomial<Rationals>,
    limits: &ComputeLimits,
    held: usize,
) -> Result<Polynomial<Rationals>, EqualityCheckError> {
    if left.ring() != right.ring() {
        return Err(EqualityCheckError::RingMismatch);
    }
    let local = operation_limits(limits, held)?;
    left.try_sub_with_limits(right, &local)
        .map_err(EqualityCheckError::from)
}

fn add(
    left: &Polynomial<Rationals>,
    right: &Polynomial<Rationals>,
    limits: &ComputeLimits,
    held: usize,
) -> Result<Polynomial<Rationals>, EqualityCheckError> {
    if left.ring() != right.ring() {
        return Err(EqualityCheckError::RingMismatch);
    }
    let local = operation_limits(limits, held)?;
    left.try_add_with_limits(right, &local)
        .map_err(EqualityCheckError::from)
}

fn lcm_shifts_with_limits(
    left: &[u16],
    right: &[u16],
    limits: &ComputeLimits,
    held: usize,
) -> Result<(Vec<u16>, Vec<u16>), EqualityCheckError> {
    if left.len() != right.len() {
        return Err(EqualityCheckError::RingMismatch);
    }
    let bytes = size_of::<u16>()
        .saturating_mul(left.len())
        .saturating_mul(2);
    check_limits(limits, held.saturating_add(bytes))?;
    let left_shift = left
        .iter()
        .zip(right)
        .map(|(&left, &right)| left.max(right) - left)
        .collect();
    let right_shift = left
        .iter()
        .zip(right)
        .map(|(&left, &right)| left.max(right) - right)
        .collect();
    Ok((left_shift, right_shift))
}

fn leading_monomial(poly: &Polynomial<Rationals>) -> &Monomial {
    &poly
        .terms
        .last()
        .expect("the basis element is nonzero")
        .mono
}

fn divides(divisor: &[u16], multiple: &[u16]) -> bool {
    divisor.iter().zip(multiple).all(|(&a, &b)| a <= b)
}

fn quotient_with_limits(
    multiple: &[u16],
    divisor: &[u16],
    limits: &ComputeLimits,
    held: usize,
) -> Result<Vec<u16>, EqualityCheckError> {
    if !divides(divisor, multiple) {
        return Err(EqualityCheckError::RingMismatch);
    }
    let bytes = size_of::<u16>().saturating_mul(multiple.len());
    check_limits(limits, held.saturating_add(bytes))?;
    Ok(multiple
        .iter()
        .zip(divisor)
        .map(|(&multiple, &divisor)| multiple - divisor)
        .collect())
}

fn map_division_error(error: DivisionStop) -> EqualityCheckError {
    match error {
        DivisionStop::ExponentLimit => EqualityCheckError::ExponentLimit {
            limit: DEGREE_LIMIT,
        },
        DivisionStop::Run(RunError::Compute(ComputeError::MemoryLimitExceeded)) => {
            EqualityCheckError::MemoryLimitExceeded
        }
        DivisionStop::Run(_) => EqualityCheckError::Timeout,
    }
}

fn map_candidate_error(error: BasisError) -> EqualityCheckError {
    match error {
        BasisError::RingMismatch => EqualityCheckError::RingMismatch,
        BasisError::ExponentLimit { limit } => EqualityCheckError::ExponentLimit { limit },
        BasisError::Timeout => EqualityCheckError::Timeout,
        BasisError::MemoryLimitExceeded => EqualityCheckError::MemoryLimitExceeded,
        error => EqualityCheckError::Candidate(error),
    }
}

impl From<ArithmeticError> for EqualityCheckError {
    fn from(error: ArithmeticError) -> Self {
        match error {
            ArithmeticError::RingMismatch | ArithmeticError::CoefficientConversion(_) => {
                EqualityCheckError::RingMismatch
            }
            ArithmeticError::ExponentLimit { limit } => EqualityCheckError::ExponentLimit { limit },
            ArithmeticError::Timeout => EqualityCheckError::Timeout,
            ArithmeticError::MemoryLimitExceeded => EqualityCheckError::MemoryLimitExceeded,
        }
    }
}

fn state_bytes(
    generators: &[Polynomial<Rationals>],
    basis: &Vec<Polynomial<Rationals>>,
    origins: &Vec<Origin>,
    pairs: &BinaryHeap<std::cmp::Reverse<Pair>>,
    temporaries: &[&Polynomial<Rationals>],
) -> usize {
    polys_bytes(generators)
        .saturating_add(polys_vec_bytes(basis))
        .saturating_add(origins_vec_bytes(origins))
        .saturating_add(pairs.capacity().saturating_mul(size_of::<Pair>()))
        .saturating_add(
            temporaries
                .iter()
                .map(|polynomial| polynomial.retained_bytes())
                .sum::<usize>(),
        )
}

fn polys_bytes(polys: &[Polynomial<Rationals>]) -> usize {
    polys_bytes_with_capacity(polys, polys.len())
}

fn polys_vec_bytes(polys: &Vec<Polynomial<Rationals>>) -> usize {
    polys_bytes_with_capacity(polys, polys.capacity())
}

fn polys_bytes_with_capacity(polys: &[Polynomial<Rationals>], capacity: usize) -> usize {
    size_of::<Vec<Polynomial<Rationals>>>()
        .saturating_add(size_of::<Polynomial<Rationals>>().saturating_mul(capacity))
        .saturating_add(polys.iter().map(Polynomial::retained_bytes).sum::<usize>())
}

fn origin_vec_bytes(origin: &Origin) -> usize {
    origin_bytes_with_capacity(origin, origin.capacity())
}

fn origin_bytes_with_capacity(origin: &[Polynomial<Rationals>], capacity: usize) -> usize {
    size_of::<Origin>()
        .saturating_add(size_of::<Polynomial<Rationals>>().saturating_mul(capacity))
        .saturating_add(origin.iter().map(Polynomial::retained_bytes).sum::<usize>())
}

fn origins_vec_bytes(origins: &Vec<Origin>) -> usize {
    origins_bytes_with_capacity(origins, origins.capacity())
}

fn origins_bytes_with_capacity(origins: &[Origin], capacity: usize) -> usize {
    size_of::<Vec<Origin>>()
        .saturating_add(size_of::<Origin>().saturating_mul(capacity))
        .saturating_add(origins.iter().map(origin_vec_bytes).sum::<usize>())
}

fn copy_data_bytes(
    ring: &PolynomialRing<Rationals>,
    exponents: &[u16],
    coefficient: &BigRational,
) -> usize {
    size_of::<u16>()
        .saturating_mul(exponents.len())
        .saturating_add(ring.ops().heap_bytes(coefficient))
}

fn term_capacity_delta<T>(terms: &Vec<T>, additional: usize) -> usize {
    if additional == 0 || terms.len() <= terms.capacity().saturating_sub(additional) {
        return 0;
    }
    let needed = terms.len().saturating_add(additional);
    let next = needed.max(terms.capacity().saturating_mul(2));
    size_of::<T>().saturating_mul(next.saturating_sub(terms.capacity()))
}

fn reserve_vec_slots<T>(
    values: &mut Vec<T>,
    additional: usize,
    held: usize,
    limits: &ComputeLimits,
) -> Result<(), EqualityCheckError> {
    let delta = term_capacity_delta(values, additional);
    if delta == 0 {
        return Ok(());
    }
    check_limits(limits, held.saturating_add(delta))?;
    let old_capacity = values.capacity();
    values.reserve_exact(additional);
    let actual_delta =
        size_of::<T>().saturating_mul(values.capacity().saturating_sub(old_capacity));
    check_limits(limits, held.saturating_add(actual_delta))
}

fn reserve_heap_slot(
    pairs: &mut BinaryHeap<std::cmp::Reverse<Pair>>,
    held: usize,
    limits: &ComputeLimits,
) -> Result<(), EqualityCheckError> {
    if pairs.len() < pairs.capacity() {
        return Ok(());
    }
    let old_capacity = pairs.capacity();
    let next_capacity = pairs
        .len()
        .saturating_add(1)
        .max(old_capacity.saturating_mul(2));
    let delta = size_of::<Pair>().saturating_mul(next_capacity.saturating_sub(old_capacity));
    check_limits(limits, held.saturating_add(delta))?;
    pairs.reserve_exact(1);
    let actual_delta =
        size_of::<Pair>().saturating_mul(pairs.capacity().saturating_sub(old_capacity));
    check_limits(limits, held.saturating_add(actual_delta))
}

fn check_limits(limits: &ComputeLimits, bytes: usize) -> Result<(), EqualityCheckError> {
    if let Some(stop) = limits.stop() {
        return Err(map_run_error(stop));
    }
    if limits.memory.is_some_and(|limit| bytes > limit) {
        return Err(EqualityCheckError::MemoryLimitExceeded);
    }
    Ok(())
}

fn residual_limits(
    limits: &ComputeLimits,
    external_bytes: usize,
) -> Result<ComputeLimits, EqualityCheckError> {
    let mut local = limits.clone();
    if let Some(limit) = limits.memory {
        local.memory = Some(
            limit
                .checked_sub(external_bytes)
                .ok_or(EqualityCheckError::MemoryLimitExceeded)?,
        );
    }
    Ok(local)
}

fn operation_limits(
    limits: &ComputeLimits,
    held: usize,
) -> Result<ComputeLimits, EqualityCheckError> {
    residual_limits(limits, held)
}

fn map_run_error(error: RunError) -> EqualityCheckError {
    match error.reported() {
        ComputeError::MemoryLimitExceeded => EqualityCheckError::MemoryLimitExceeded,
        _ => EqualityCheckError::Timeout,
    }
}
